<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INBL01LAP30343" failures="1" tests="5" name="Test1" time="102.428" errors="0" timestamp="2023-03-31T15:45:20 IST">
  <testcase classname="com.hag.tests.Scenario_1" name="logininTotheapplicaton" time="1.375"/>
  <testcase classname="com.hag.tests.Scenarios_2" name="checkTheParticularProduct" time="0.563"/>
  <testcase classname="com.hag.tests.Scenario_3" name="validateThePrice" time="2.15"/>
  <testcase classname="com.hag.tests.Scenario_4$Scenarios_4" name="valiadteErroMessage" time="0.27">
    <failure type="java.lang.AssertionError" message="ERROR MESSAGE IS NOT SAME   expected [Epic sadface: Username and password do not match any user in this service12] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: ERROR MESSAGE IS NOT SAME   expected [Epic sadface: Username and password do not match any user in this service12] but found [Epic sadface: Username and password do not match any user in this service]
at com.hag.tests.Scenario_4$Scenarios_4.valiadteErroMessage(Scenario_4.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- valiadteErroMessage -->
  <testcase classname="com.hag.tests.Scenario_5" name="featuresOfRealDeviceCloud" time="43.439"/>
</testsuite> <!-- Test1 -->
